### ISSUE TITLE
Error 500 when searching for keyword

### ISSUE THREAD

**Issue by niksy** [chubin/cheat.sh#323]
Internal server error is thrown everytime I try to search for keyword, e.g. `curl cheat.sh/~redirect`. Same thing happens on website and when using via `curl`.

**Comment by abitrolly** [comment]
Try https://cheat.sh/curl+redirect instead?

**Comment by niksy** [comment]
I was looking for keyword `redirect` specifically, i.e. results for either `curl` or redirecting standard error and output.

**Comment by abitrolly** [comment]
Then the URL that gives 500 error should be https://cheat.sh/~redirect because `curl.sh/~redirect` is a different site.

**Comment by niksy** [comment]
Sorry, I’ve switched `curl` with `cheat`. Updated original post.

**Comment by estiens** [comment]
yeah, I get a 500 error from most requests it can't quite parse it seems

**Comment by chubin** [comment]
Should be fixed now, please test.

**Comment by niksy** [comment]
@chubin it works now, but queries like `/scala/~closure` or `/~snapshot/r` still don’t work.

**Comment by chubin** [comment]
Please check it again

**Comment by niksy** [comment]
It works now, at least it doesn’t throw 500; for example `/scala/~closure` doesn’t return anything.

**Comment by chubin** [comment]
I suppose that it is correct in this case, but maybe we should return some "nothing found" message explicitly.
This query searches for `closure` in the scala cheat sheets, not on external resources, and so there are no `closure` occurrences there. Compare it with `/scala/~loop` or `/scala/~function`, for example

**Comment by niksy** [comment]
Yeah, that should probably make more sense. Closing this issue since original problem has been solved!
